### ISSUE TITLE
nano

### ISSUE THREAD

**Issue by rhaleblian** [yoyodyne-research/BaCKSTEP#1]
`codepoet80` at nextcomputers.org is looking at this.
`pomosapiens` at nextcomputers.org is looking at the dependencies.

**Comment by rhaleblian** [comment]
codepoet is on 4.2.
@rhaleblian (pomosapiens) is on 3.3.

**Comment by rhaleblian** [comment]
`nano` looks like a long road that may end in a dead end.

I published `pico` extracted from an Installer.app pkg of `pine`, as a substitute:

http://next.haleblian.com/unix/pico-4.64.NIHS.b.tar.Z

http://next.haleblian.com/document/pomosapien/pico.png

**Comment by rhaleblian** [comment]
If immediate stakeholders can live with `pico`, close this.

**Comment by codepoet80** [comment]
I can definitely live with pico -- thank you for investigating!

**Comment by rhaleblian** [comment]
Ok, with other things to do, let's move on!
